### ISSUE TITLE
* at beginning/end of string

### ISSUE THREAD

**Issue by stevenvachon** [lnwdr/calmcard#1] opened 2015-08-14 15:22 UTC
```js
calmcard("keywords",  "keyword*");  //-> true
calmcard("a keyword", "*keyword");  //-> true

calmcard("keyword", "keyword*");  //-> false
calmcard("keyword", "*keyword");  //-> false
```

It'd be less technical for user input to support the `"*"` wildcard even in cases where it goes beyond the first/last character index.

**Comment by lnwdr** [comment] 2015-08-16 14:00
I'm not sure what the issue here is. If your user input contains `*` character at the beginning or end, you can trim them right before using the `calmcard()` on it to ignore them completely.

**Comment by stevenvachon** [comment] 2015-08-16 14:46
Trimming would entail that I could predict user input:
```js
calmcard("http://domain.com/", "domain.com*");  //-> true
calmcard("http://domain.com", "domain.com*");  //-> false
```

**Comment by lnwdr** [comment] 2015-08-16 16:15
Are you perhaps mixing up the argument order? The pattern is the first argument of `calmcard()`.

Maybe a regular expression is more suited for your use case. What are your users entering and what are you trying to do with it? Please provide some more information than just two lines of code so I can understand what you are trying to achieve.

**Comment by stevenvachon** [comment] 2015-08-16 16:51
Yes, I had the arguments backwards.

I am providing URL keyword exclusion for [broken-link-checker](https://npmjs.com/broken-link-checker)'s `excludedKeywords` option.

**Comment by lnwdr** [comment] 2015-08-17 10:22
For that use case I'd suggest using regular expressions. Calmcard`s purpose is to check for exact matches of a pattern, not for matches of substrings.

You could still only allow `*` as the only wildcard but then replace it with `.*` before matching it as a regex. That should cover your case, when the keyword is a t the start/end of a string.

**Comment by stevenvachon** [comment] 2015-08-17 17:08
I'd also have to comment out all other wildcards. This is becoming its own lib, then, which will need tests. I was trying to avoid more custom code.

**Comment by lnwdr** [comment] 2015-08-18 14:48
Since your docs on that feature of your library already say "glob pattern", you could use one of the existing sort-of glob implementations in JS. Afaik all of them use regular expressions internally which is why they aren't really glob implementations. Calmcard provides far less functionality than glob.

**Comment by stevenvachon** [comment] 2015-08-18 20:01
A wildcard is like a glob. A "glob" doesn't have a spec. The "wildcard" package does what I need, but its documentation doesn't currently reflect the implementation.

**Comment by lnwdr** [comment] 2015-08-19 11:46
This discussion is going nowhere. I'm going to close this issue since it's definitely not a bug and I currently don't invest time into feature requests for this lib.

I wrote Calmcard to explicitly be a simpler matching mechanism than typical UNIX glob patterns and to avoid regular expressions. Your use case is beyond its scope and not really compatible with its purpose (matching complete strings, not substrings).

**Closed by lnwdr** 2015-08-19 11:46 UTC
